"""
Signal — an objective observation from the rules engine or market data.

Signals are NOT recommendations. They are facts:
  - "Your equity allocation drifted 9% above target"
  - "Emergency fund is at 3.2 months (below 6-month threshold)"
  - "Nifty corrected 5% this week"
  - "CAS not uploaded in 42 days"
  - "Salary credited today; ₹1.8L idle in savings"

The recommendation engine READS signals and turns them into
prioritised, actionable suggestions. Keeping these separate makes
the system auditable — you can always trace a recommendation back
to the exact signals that triggered it.

Signals are generated by:
  - Rules engine (deterministic Python checks)
  - Market data sync (price thresholds, index movements)
  - Document pipeline (staleness alerts, parse completions)
"""

from datetime import datetime
from enum import Enum
from typing import Optional
from beanie import Document
from pydantic import Field


class SignalType(str, Enum):
    # Portfolio health
    ALLOCATION_DRIFT = "allocation_drift"
    CONCENTRATION_BREACH = "concentration_breach"
    REBALANCE_CANDIDATE = "rebalance_candidate"
    UNDERPERFORMANCE = "underperformance"
    # Goal-related
    GOAL_UNDERFUNDED = "goal_underfunded"
    GOAL_ON_TRACK = "goal_on_track"
    GOAL_ALLOCATION_MISMATCH = "goal_allocation_mismatch"
    # Cash management
    IDLE_CASH_DETECTED = "idle_cash_detected"
    SALARY_CREDITED = "salary_credited"
    LOW_LIQUIDITY = "low_liquidity"
    EMERGENCY_FUND_LOW = "emergency_fund_low"
    # Market
    MARKET_DRAWDOWN = "market_drawdown"
    MARKET_RALLY = "market_rally"
    ASSET_CLASS_MOMENTUM = "asset_class_momentum"
    VALUATION_EXTREME = "valuation_extreme"     # P/E at extreme
    # Technical / price-based
    TECHNICAL_DRAWDOWN = "technical_drawdown"           # Price far below 52W high
    TECHNICAL_MOMENTUM_STRONG = "technical_momentum_strong"  # Near 52W high, review if overweight
    TECHNICAL_HIGH_VOLATILITY = "technical_high_volatility"  # Annual vol above threshold
    TECHNICAL_NEAR_52W_LOW = "technical_near_52w_low"   # In bottom band of 52W range
    # Fundamental
    FUNDAMENTAL_CONCERN = "fundamental_concern"          # Low ROE, high debt, loss-making P/E
    # Corporate actions
    CORPORATE_ACTION_DIVIDEND = "corporate_action_dividend"
    CORPORATE_ACTION_BONUS = "corporate_action_bonus"
    CORPORATE_ACTION_SPLIT = "corporate_action_split"
    CORPORATE_ACTION_RIGHTS = "corporate_action_rights"   # Urgent — decision required
    CORPORATE_ACTION_BUYBACK = "corporate_action_buyback" # Urgent — tender window
    # Document housekeeping
    DOCUMENT_STALE = "document_stale"
    DOCUMENT_MISSING = "document_missing"
    # Policy violation
    POLICY_VIOLATION = "policy_violation"


class SignalSeverity(str, Enum):
    URGENT = "urgent"       # Immediate Telegram push
    NORMAL = "normal"       # Include in weekly digest
    INFO = "info"           # Log only, don't surface to user


class Signal(Document):
    """
    One objective observation. Consumed by the recommendation engine.

    data_freshness_score (0-1) reflects how fresh the underlying data is.
    A signal with score < 0.5 will be downweighted in recommendation scoring
    and shown to the user with a "based on data from X days ago" caveat.
    """

    signal_type: SignalType
    severity: SignalSeverity

    title: str                                  # Short display title
    description: str                            # Human-readable explanation
    data: dict = Field(default_factory=dict)   # Structured context (values, thresholds, etc.)
    data_freshness_score: float = 1.0          # 0-1, time-decay weighted

    # References (flexible — signals can relate to multiple things)
    related_instrument_ids: list[str] = Field(default_factory=list)
    related_goal_ids: list[str] = Field(default_factory=list)
    related_account_ids: list[str] = Field(default_factory=list)

    # Lifecycle
    generated_at: datetime = Field(default_factory=datetime.utcnow)
    is_resolved: bool = False
    resolved_at: Optional[datetime] = None
    resolution_note: Optional[str] = None

    # Prevent duplicate signals for the same condition in same week
    dedup_key: Optional[str] = None

    class Settings:
        name = "signals"